name: Build

on:
- push

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v12
    - uses: DeterminateSystems/magic-nix-cache-action@v7
    - name: Build
      run: nix run .#build

